name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      # 1. Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests and always generate JUnit XML
      - name: Run tests
        id: pytest
        run: |
          pytest -v --junitxml=test-results.xml || echo "Tests failed, XML generated for artifact"

      # 5. Upload test-results artifact only if there are failures
      - name: Upload failing test results
        if: failure()  # only run this step if previous step failed
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
